logger: 
  class_path: pytorch_lightning.loggers.WandbLogger
  init_args:
    project: 'local_contact'
    name: 'test'
    entity: 'contact-estimation'
    # save_code: True
    log_model: 'all'
    offline: False
    notes: 'test'
callbacks:
# callback to save the best model
- class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  init_args:
  # https://github.com/Lightning-AI/lightning/discussions/5782 about automatic addition of dataloader_idx
    monitor: 'val_NMS_monolithic_epoch'
    mode: 'min'
    save_top_k: 1
    save_last: True
    filename: '{epoch:02d}-{val_loss:.2f}'
    every_n_epochs: 1
    verbose: True
    save_on_train_epoch_end: True